from blog.models import Post,Category
from django.core.management.base import BaseCommand
from typing import Any
import random
class Command(BaseCommand):
    help="This command insert post data"

    def handle(self, *args: Any, **options: Any):
        # delete the existing data
        Post.objects.all().delete()

        title = [
        "10 Tips for Better Time Management",
        "A Beginner's Guide to Meal Prepping",
        "How to Start a Morning Routine That Sticks",
        "The Basics of Personal Finance",
        "Why Reading Every Day Changes Your Life",
        "Simple Home Workouts for Busy People",
        "How to Stay Productive While Working From Home",
        "A Guide to Minimalist Living",
        "Top 5 Destinations for Solo Travelers",
        "Understanding the Basics of Investing",
        "How to Build Healthy Sleep Habits",
        "The Art of Effective Communication",
        "Beginner's Guide to Growing Your Own Vegetables",
        "How to Overcome Procrastination",
        "5 Ways to Reduce Stress Daily",
        "The Importance of Setting Realistic Goals",
        "A Simple Guide to Journaling",
        "How to Improve Your Focus and Concentration",
        "Budget-Friendly Meal Ideas for the Week",
        "Tips for Building Better Habits",
        ]

        content = [
                "Learn how to prioritize tasks, avoid distractions, and make the most of your day with these simple time management strategies. Start by identifying your top three priorities each morning before checking email or messages, since reactive habits like inbox-checking can hijack your entire schedule before you've even begun. Break larger projects into smaller, manageable chunks so they feel less overwhelming and easier to start. Use time-blocking to dedicate specific hours to focused work, and protect that time fiercely by turning off notifications and closing unnecessary browser tabs. Don't forget to schedule short breaks — they actually improve concentration rather than hurting it, since the brain isn't built for hours of uninterrupted focus. Reviewing your day the evening before can also help you hit the ground running instead of wasting the first hour figuring out what to do. With consistent practice, these habits can transform how much you accomplish in a day, reducing stress while increasing the sense of control you have over your time.",

                "Meal prepping can save you time and money while helping you eat healthier. Here's how to get started as a beginner. Pick one day a week, like Sunday, to plan and cook meals in bulk so weekday decision fatigue around food disappears entirely. Invest in a few good quality containers that make portioning and storing food simple, ideally ones that are microwave and freezer safe. Start small — prep just three or four meals at first instead of trying to plan an entire week, since overcommitting early is the most common reason people abandon meal prepping. Keep your recipes simple, using ingredients that reheat well and don't lose texture, like grains, roasted vegetables, and proteins that hold up over several days. Buying ingredients in bulk when they're on sale can also stretch your grocery budget further. Over time, you'll find a rhythm that fits your schedule and taste preferences, turning what once felt like a chore into an efficient weekly ritual that frees up your evenings.",

                "A consistent morning routine can set the tone for your entire day. Discover the habits that make mornings easier and less chaotic. Waking up at the same time daily helps regulate your body's internal clock and improves sleep quality over the long run, even on weekends when the temptation to sleep in is strongest. Avoid checking your phone the moment you wake up — give yourself a few minutes of calm first before being pulled into emails, news, or social media. Incorporate movement, even if it's just five minutes of stretching, to boost energy levels and circulation before the day gets busy. A few minutes of quiet reflection, planning, or journaling can help you approach the day with more clarity and intention rather than reacting to whatever comes first. Preparing small things the night before, like laying out clothes or packing a bag, also reduces morning friction. Small, repeatable actions each morning compound into big changes over time, creating a sense of stability no matter what the rest of the day holds.",

                "Understanding budgeting, saving, and spending wisely are the first steps toward financial freedom. Start by tracking every expense for a month to see where your money actually goes, since most people are surprised by how much slips through on small, unplanned purchases. Create a simple budget that separates needs, wants, and savings goals, giving every dollar a clear purpose before it's spent. Automate your savings so a portion of every paycheck is set aside before you're tempted to spend it, removing willpower from the equation entirely. Avoid lifestyle inflation — as your income grows, resist the urge to increase spending at the same pace, and instead redirect that extra income toward savings or investments. Building an emergency fund of three to six months' expenses provides a critical safety net for unexpected costs. Building these habits early creates a strong foundation for long-term financial stability, making future goals like homeownership or retirement feel far more achievable.",

                "Reading daily boosts knowledge, reduces stress, and improves focus. Here's why you should make it a habit. Even just 20 minutes a day can expose you to new ideas and perspectives you wouldn't otherwise encounter, broadening how you think about the world. Reading before bed, instead of scrolling on your phone, can also improve sleep quality by avoiding the blue light and mental stimulation that screens produce. Choose a mix of fiction and non-fiction to keep your reading habit enjoyable and varied, since forcing yourself through material you don't enjoy is a common reason people quit. Carrying a book or e-reader with you makes it easy to read during small pockets of downtime, like commutes or waiting rooms, that would otherwise be lost to your phone. Joining a book club or discussing what you read with others can also deepen understanding and keep you motivated. Over time, consistent reading sharpens vocabulary, empathy, and critical thinking skills in ways that compound far beyond the pages themselves.",

                "You don't need a gym to stay fit. These simple workouts can be done at home in under 30 minutes with little to no equipment required. Bodyweight exercises like squats, push-ups, and lunges build strength without any equipment, making them ideal for beginners or anyone short on space. Adding short bursts of cardio, like jumping jacks or high knees, keeps your heart rate up and adds an aerobic component to the routine. Consistency matters more than intensity, so aim for a routine you can realistically stick to three or four times a week rather than an unsustainable daily grind. Stretching before and after your workout helps prevent injury and improves flexibility over time, and shouldn't be skipped even when short on time. Tracking your progress, even informally, helps keep motivation high as you notice improvements in strength and endurance. With just a bit of floor space, you can build a solid fitness habit from home that fits into even the busiest schedule.",

                "Working from home comes with unique challenges. Learn how to stay focused and productive throughout the day despite the many distractions competing for your attention. Setting up a dedicated workspace, even a small corner, helps your brain associate that area with focus and makes it easier to mentally clock in and out. Establishing clear work hours prevents tasks from bleeding into your personal time, which is one of the most common complaints among remote workers. Taking regular breaks away from your screen can actually improve concentration when you return, since sustained focus without rest leads to diminishing returns. Minimizing distractions, like silencing notifications during deep work sessions, makes a noticeable difference in how much you get done. Communicating clearly with colleagues about your availability also helps set expectations and reduces unnecessary interruptions. With the right boundaries and structure, remote work can be just as productive as an office, while offering flexibility that traditional workplaces often can't.",

                "Minimalism isn't about owning less for the sake of it — it's about making room for what truly matters in your life. Start small by decluttering one drawer or shelf at a time instead of tackling your whole home at once, which often leads to burnout and abandoned projects. Ask yourself whether each item adds real value or just takes up space, both physically and mentally. Letting go of things you no longer use can create a surprising sense of mental clarity and reduce the low-level stress that clutter often causes. Minimalism also extends beyond physical items — simplifying your schedule and commitments matters just as much as clearing out a closet. Being intentional about what you bring into your life going forward, rather than just decluttering once, is key to maintaining the benefits long term. Over time, this intentional approach to living can reduce stress and increase focus on what you truly value, whether that's relationships, experiences, or personal growth.",

                "Traveling alone can be one of the most rewarding experiences, offering a kind of freedom that group travel rarely allows. Here are five destinations perfect for solo explorers looking for their next adventure. Choosing a destination with a strong sense of safety and walkability makes solo travel far less stressful, especially for first-time solo travelers. Staying in hostels or guesthouses is a great way to meet fellow travelers along the way and combat the isolation that can sometimes come with traveling alone. Planning a loose itinerary, rather than a rigid one, leaves room for spontaneous discoveries and unexpected detours that often become trip highlights. Solo travel pushes you outside your comfort zone in ways that build confidence and independence you can carry into everyday life. Learning a few basic phrases in the local language also goes a long way in navigating unfamiliar places. Whether it's a quiet countryside or a bustling city, traveling alone offers a unique kind of freedom that's worth experiencing at least once.",

                "Investing doesn't have to be complicated. This guide breaks down the basics for beginners looking to grow their money without feeling overwhelmed. Start by understanding the difference between stocks, bonds, and index funds before committing any money, since each carries a different level of risk and potential return. Diversifying your investments helps spread risk instead of relying on a single asset, protecting you from the volatility of any one company or sector. Investing consistently over time, even small amounts, benefits from the power of compound growth, which rewards patience far more than timing the market ever could. Avoid the temptation to chase short-term trends and instead focus on long-term strategy built around your actual financial goals. Automating contributions to your investment accounts removes emotion from the process and builds the habit effortlessly. With patience and a bit of research, anyone can start building wealth through investing, regardless of how much they're starting with.",

                "Quality sleep is essential for health and productivity, yet it's often the first thing sacrificed in a busy schedule. Learn how to build habits that improve your sleep quality night after night. Keeping a consistent sleep schedule, even on weekends, helps regulate your body's natural rhythm and makes falling asleep far easier. Avoiding screens at least 30 minutes before bed can reduce blue light exposure and improve melatonin production, helping your body wind down naturally. Creating a calming bedtime routine, like reading or light stretching, signals to your body that it's time to relax. Keeping your bedroom cool, dark, and quiet supports deeper, more restorative sleep throughout the night. Limiting caffeine intake in the afternoon and evening can also make a significant difference for many people. Prioritizing sleep isn't a luxury — it's one of the most impactful things you can do for your overall wellbeing, affecting everything from mood to immune function to long-term health.",

                "Clear and effective communication can improve relationships, both personal and professional. Here's how to master it, one conversation at a time. Active listening, rather than simply waiting for your turn to speak, builds trust and understanding between you and whoever you're talking to. Being direct and specific about your needs reduces confusion and misunderstandings that often build resentment over time. Nonverbal cues, like tone and body language, often communicate just as much as words themselves, so being mindful of them matters as much as what you say. Practicing empathy allows you to consider the other person's perspective before responding, which often diffuses tension before it escalates. Asking clarifying questions instead of assuming intent can prevent countless unnecessary conflicts. With consistent effort, better communication can strengthen every relationship in your life, from close friendships to professional collaborations, making both easier and more fulfilling.",

                "Growing your own vegetables is easier than you think, even without a large backyard or years of gardening experience. Start your first garden with these beginner-friendly tips that set you up for success. Choose easy-to-grow vegetables like tomatoes, lettuce, or herbs for your first attempt, since they're forgiving and produce visible results quickly. Make sure your garden gets enough sunlight, ideally six or more hours a day, as insufficient light is one of the most common reasons plants fail to thrive. Consistent watering, without overdoing it, is key to healthy plant growth, and a simple finger test in the soil can tell you when it's time. Starting with a small raised bed or containers makes gardening manageable even with limited space, and reduces the risk of poor native soil quality. Learning to recognize common pests and addressing them early can save an entire harvest. With a bit of patience, you'll be harvesting your own fresh produce in no time, and gaining a rewarding new skill along the way.",

                "Procrastination affects everyone at some point, but it doesn't have to control your productivity. Learn practical strategies to overcome it and get things done consistently. Breaking large tasks into smaller steps makes them feel less intimidating and easier to start, since the sheer size of a project is often what triggers avoidance in the first place. The two-minute rule — doing any task that takes less than two minutes immediately — can build momentum and prevent small tasks from piling up. Removing distractions from your environment reduces the temptation to delay work, whether that means silencing your phone or closing unrelated browser tabs. Setting clear deadlines, even self-imposed ones, adds a sense of urgency that helps you stay on track when there's no external pressure. Understanding the emotional root of your procrastination, whether it's fear of failure or perfectionism, can also help address it at the source. With consistent practice, these strategies can help turn procrastination into productive action, one small step at a time.",

                "Daily stress can take a toll on your mental health if left unmanaged for too long. Try these five simple techniques to manage it effectively before it builds up. Deep breathing exercises can quickly calm your nervous system during stressful moments, offering a fast and accessible tool anywhere you are. Regular physical activity is one of the most effective natural stress relievers available, releasing tension built up throughout the day. Setting boundaries around your time and energy prevents burnout before it starts, especially when it comes to overcommitting to others' demands. Practicing gratitude, even briefly each day, can shift your mindset toward positivity and reduce the mental weight of daily stressors. Talking to someone you trust about what's weighing on you can also provide perspective and relief. Small, consistent habits like these can make daily stress far more manageable over time, protecting both your mental and physical health in the long run.",

                "Setting realistic, achievable goals is key to long-term success, yet many people struggle to follow through on the goals they set. Learn how to set goals that actually stick this time around. Start by making your goals specific and measurable, rather than vague aspirations that are hard to track or feel motivated by. Breaking big goals into smaller milestones makes progress easier to track and celebrate along the way, keeping motivation high even before you reach the finish line. Writing your goals down increases accountability and keeps them top of mind, especially when placed somewhere you'll see regularly. Reviewing and adjusting your goals regularly ensures they stay relevant as circumstances change, rather than clinging to a plan that no longer fits your life. Sharing your goals with someone else can also add a layer of accountability that solo goal-setting often lacks. With the right approach, goal-setting becomes a powerful tool for turning intentions into real, lasting results.",

                "Journaling is a powerful tool for self-reflection and mental clarity, and it's far simpler to start than most people assume. Here's a simple guide to get started today. Set aside just five to ten minutes a day to write freely without worrying about grammar or structure, since the goal is honesty, not polish. Prompts like 'What am I grateful for today?' can help when you're not sure what to write, especially in the early days of building the habit. Journaling can help process emotions and identify patterns in your thoughts and behavior over time that might otherwise go unnoticed. There's no right or wrong way to do it — consistency matters more than perfection, and even short, messy entries count. Keeping your journal somewhere visible, like on your nightstand, can serve as a helpful reminder to stick with it. Over weeks and months, journaling can become a valuable habit for personal growth, offering a written record of how far you've come.",

                "Struggling to stay focused? These techniques can help improve your concentration and productivity, even in a world full of distractions. The Pomodoro technique, working in short focused bursts with breaks in between, can boost sustained attention by working with your brain's natural limits rather than against them. Eliminating multitasking and focusing on one task at a time improves both speed and quality of work, despite the common belief that multitasking saves time. Creating a distraction-free environment, including silencing notifications and closing unrelated tabs, makes a noticeable difference in how deeply you can focus. Regular exercise and adequate sleep also play a bigger role in focus than most people realize, since a tired or restless body struggles to concentrate no matter the strategy used. Taking short walks between tasks can also help reset your attention span. With practice, these techniques can help you get more done in less time, while feeling far less mentally drained by the end of the day.",

                "Eating well on a budget is possible with the right planning, even when grocery prices feel like they're constantly rising. Check out these affordable meal ideas for the week ahead. Buying in-season produce and staple ingredients like rice, beans, and eggs keeps costs low while still providing solid nutrition. Planning meals around sales and what you already have on hand reduces food waste and unnecessary spending at the store. Batch cooking larger portions and freezing extras saves both time and money later in the week, especially on busier days when cooking feels impossible. Simple, whole-food meals are often cheaper and healthier than pre-packaged alternatives, despite convenience foods seeming like the easier option. Shopping with a list, and sticking to it, also helps avoid impulse purchases that quietly add up. With a bit of planning, eating well doesn't have to strain your budget, proving that healthy eating and affordability aren't mutually exclusive.",

                "Building better habits takes time and consistency, and understanding the science behind habit formation can make the process far more effective. Learn the science-backed strategies that actually work, rather than relying on willpower alone. Start small — tiny, manageable changes are far more sustainable than drastic overhauls that are difficult to maintain past the first few weeks. Habit stacking, or attaching a new habit to an existing routine, makes it easier to remember and stick with, since it piggybacks on behavior you already do automatically. Tracking your progress, even simply with a checklist or app, reinforces motivation and accountability along the way. Expect setbacks along the way — consistency over time matters more than perfection, and missing one day doesn't erase the progress you've made. Rewarding yourself for milestones, even small ones, can also help reinforce the behavior you're trying to build. With patience and the right strategies, lasting habits can be built one small step at a time, eventually becoming second nature.",
        ]

        img_url = [f"https://picsum.photos/id/{i}/800/400" for i in range(1, 21)]
        
        categories = Category.objects.all()
        for t, c, img in zip(title, content, img_url):
            category =random.choice(categories)
            Post.objects.create(title=t, content=c, img_url=img,category=category)
        self.stdout.write(self.style.SUCCESS("Completed inserting data!")) 
